let a = String(123)
let b = Number(123)
let c = Boolean(123)
let d = BigInt(123)
let e = Object(123)
console.log(typeof(a))
console.log(typeof(b))
console.log(c)
console.log(typeof(c))
console.log(d)
console.log(typeof(d))
console.log(e)

console.log("*******************");

let a1 = String("abc123")
let b1 = Number("abc123")
let c1 = Boolean("abc123")
let e1 = Object("abc123")
console.log(typeof(a1))
console.log(typeof(b1))
console.log(c1)
console.log(typeof(c1))
console.log(d1)
console.log(typeof(d1))
console.log(e1)